#!/bin/bash

if ! which magick 2>/dev/null; then
  echo "No 'magick' installed. Install 'magick' CLI first."
  exit 1
fi

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Must provide input and output folders."
  echo "Usage: $0 [input] [output]"
  exit 1
fi

if ! [ -d "$1" ]; then
  echo "'$1' is not a directory"
  exit 1
fi

if ! [ -d "$2" ]; then
  echo "'$2' is not a directory"
  exit 1
fi

is_supported() {
  accepted_ext=("tiff" "tif" "png")
  for ext in ${accepted_ext[@]}; do
    # echo "is ${1##*.}" is equal to "${ext}?"
    if [ "${1##*.}" = "${ext}" ]; then
      # echo "> yes"
      return 0
    fi
    # echo "> no"
  done
  # echo "${1} is not supported"
  return 1
}

echo "Converting files in $1/ and outputting them in $2/"

for file in $1/*; do
  if is_supported "${file}"; then
    no_ext_name="${file%.*}"
    output_name=$(basename "${no_ext_name}")
    magick -verbose "${file}" "$2/${output_name}.jpeg"
  else
    echo "Skipping file '${file}'..."
  fi
done
