name: Build

on:
  workflow_dispatch:
    inputs:
      release:
        description: Is it a release build?
        type: boolean
        required: false
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          use_api: true
          scheme: semver
          increment: patch
    outputs:
      version: ${{ inputs.release && steps.version.outputs.current-version || steps.version.outputs.version }}
  build-mac:
    needs: bump-version
    uses: ./.github/workflows/rust.yml
    with:
      platform: macos
      version: ${{ needs.bump-version.outputs.version }}
      build-type: ${{ inputs.release && 'release' || 'debug' }}
  build-linux:
    needs: bump-version
    uses: ./.github/workflows/rust.yml
    with:
      platform: ubuntu
      version: ${{ needs.bump-version.outputs.version }}
      build-type: ${{ inputs.release && 'release' || 'debug' }}
  build-win:
    needs: bump-version
    uses: ./.github/workflows/rust.yml
    with:
      platform: windows
      version: ${{ needs.bump-version.outputs.version }}
      build-type: ${{ inputs.release && 'release' || 'debug' }}
