name: Build

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-batch-converter
          path: target/debug/image-batch-converter
  deploy:
    runs-on: macos-13
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-batch-converter
          path: /opt
      - name: List artifacts
        run: ls /opt
