name: Build Debug

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: imabacon-macos
          path: target/debug/imabacon
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: imabacon-linux
          path: target/debug/imabacon
