name: Build for Platform

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      version:
        required: true
        type: string
      build-type:
        required: true
        type: string


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ inputs.platform }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --profile ${{ inputs.build-type }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: imabacon-${{ inputs.platform }}-${{ inputs.version }}"
          path: target/${{ inputs.build-type }}/imabacon
